/** @format */

export const carousels = [
    {
        id: 1,
        alt: "carosel 1",
        imgUrl: "/assets/caresol_1.png",
    },
    {
        id: 2,
        alt: "carosel 7",
        imgUrl: "/assets/carosel_2.png",
    },
    {
        id: 3,
        alt: "carosel 6",
        imgUrl: "/assets/carosel_3.png",
    },
    {
        id: 4,
        alt: "carosel 4",
        imgUrl: "/assets/carosel_4.png",
    },
    {
        id: 5,
        alt: "carosel 5",
        imgUrl: "/assets/carosel_5.jpg",
    },
];

export const categories = [
    {
        id: 1,
        title: "galaxy discout",
        img: "/assets/category_1.jpg",
    },
    {
        id: 2,
        title: "Top quality used",
        img: "/assets/cat_2.jpg",
    },
    {
        id: 3,
        title: "Used phone...",
        img: "/assets/cat_3.jpg",
    },
    {
        id: 4,
        title: "sell",
        img: "/assets/cat_4.jpg",
    },
    {
        id: 5,
        title: "service introduct...",
        img: "/assets/cat_5.jpg",
    },
    {
        id: 6,
        title: "Game device",
        img: "/assets/cat_6.jpg",
    },
    {
        id: 7,
        title: "Apple",
        img: "/assets/cat_7.jpg",
    },
    {
        id: 8,
        title: "Winter SALE",
        img: "/assets/cat_8.jpg",
    },
    {
        id: 9,
        title: "Smartphone",
        img: "/assets/cat_9.jpg",
    },
    {
        id: 10,
        title: "view all",
        img: "/assets/cat_10.jpg",
    },
];

export const section_1s = [
    {
        id: 1,
        name: "[1000 Won Deal] Requip Large Capacity Air Fryer Oven 20L LAF-MOS20",
        imgUrl: "/assets/product_3.jpeg",
        price: "1000",
        discount: "7% ",
        like: 3,
        isDiscount: true,
        isSupprised: false,
        isReturned: true,
    },
    {
        id: 2,
        name: "[Genuine Special Price] Logitech Genuine MX KEYS S AS Warranty",
        imgUrl: "/assets/x_box.jpeg",
        price: "120,300",
        discount: "50% ",
        like: 3,
        isDiscount: true,
        isSupprised: true,
        isReturned: true,
    },
    {
        id: 3,
        name: "[1000 Won Deal] Sony WH-1000XM5",
        imgUrl: "/assets/product_4.jpeg",
        price: "1500",
        discount: "25% ",
        like: 3,
        isDiscount: true,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 4,
        name: "[Genuine Special Price] Logitech Genuine MX KEYS S AS Warranty",
        imgUrl: "/assets/tablet_galaxy.jpeg",
        price: "1000",
        discount: "5% ",
        like: 7,
        isDiscount: true,
        isSupprised: false,
        isReturned: true,
    },
    {
        id: 5,
        name: "[Genuine Special Price] Logitech Genuine MX KEYS S AS Warranty",
        imgUrl: "/assets/tablet_galaxy.jpeg",
        price: "1000",
        discount: "7% ",
        like: 7,
        isDiscount: true,
        isSupprised: false,
        isReturned: true,
    },
];

export const section_2s = [
    {
        id: 1,
        name: "144 languages ​​AI translator WooAsk G5K PRO Bluetooth speaker bar real-time interpreter",
        imgUrl: "/assets/power_bank.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 2,
        name: "Galaxy Tab S9 FE WIFI 128GB (SM-X510)",
        imgUrl: "/assets/tablet_galaxy.jpeg",
        price: "499.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 3,
        name: "[One month trial fee 29,900 won] Bose genuine smart ultra sound bar",
        imgUrl: "/assets/sound_bar.jpeg",
        price: "1999.99",
        discount: "",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 4,
        name: "144 languages ​​AI translator WooAsk G5K PRO Bluetooth speaker bar real-time interpreter",
        imgUrl: "/assets/product_3.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 5,
        name: "Galaxy Tab S9 FE WIFI 128GB (SM-X510)",
        imgUrl: "/assets/product_4.jpeg",
        price: "499.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
];

export const section_3s = [
    {
        id: 1,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_1.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 2,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_2.jpeg",
        price: "499.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 3,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_3.jpeg",
        price: "1999.99",
        discount: "",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 4,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_4.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 5,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_5.jpeg",
        price: "499.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
];

export const section_4s = [
    {
        id: 1,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_1.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 2,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_2.jpeg",
        price: "499.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 3,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_3.jpeg",
        price: "1999.99",
        discount: "",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 4,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_4.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 5,
        name: "Bokuk Premium Carbon Mat BKB-DC221S Single / BKB-DC222K King",
        imgUrl: "/assets/matress_5.jpeg",
        price: "499.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
];

export const section_logitech = [
    {
        id: 1,
        name: "[NEW] Logitech Genuine G PRO",
        imgUrl: "/assets/keyboard.jpeg",
        price: "299.99",
        discount: "25% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: true,
    },
    {
        id: 2,
        name: "[Genuine Special Price] Logitech Genuine MX KEYS S AS Warranty",
        imgUrl: "/assets/mouse_1.jpeg",
        price: "599.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 3,
        name: "[Genuine Special Price] Logitech Genuine MX KEYS S AS Warranty",
        imgUrl: "/assets/mouse_3.jpeg",
        price: "99.99",
        discount: "",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 4,
        name: "[Genuine Special Price] Logitech Genuine MX KEYS S AS Warranty",
        imgUrl: "/assets/mouse_3.jpeg",
        price: "299.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 5,
        name: "[Genuine Special Price] Logitech Genuine MX KEYS S AS Warranty",
        imgUrl: "/assets/mouse_4.webp",
        price: "49.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
];

export const section_kitchen = [
    {
        id: 1,
        name: "Tefal Cook For Me Smart Pressure Cooker (CY851AKR)",
        imgUrl: "/assets/kicken_1.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 2,
        name: "Tefal Cook For Me Smart Pressure Cooker (CY851AKR)",
        imgUrl: "/assets/kicken_2.jpeg",
        price: "599.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 3,
        name: "Tefal Cook For Me Smart Pressure Cooker (CY851AKR)",
        imgUrl: "/assets/kicken_3.jpeg",
        price: "99.99",
        discount: "",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 4,
        name: "Tefal Cook For Me Smart Pressure Cooker (CY851AKR)",
        imgUrl: "/assets/kicken_2.jpeg",
        price: "299.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 5,
        name: "Tefal Cook For Me Smart Pressure Cooker (CY851AKR)",
        imgUrl: "/assets/kicken_1.jpeg",
        price: "49.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
];

export const section_lg = [
    {
        id: 1,
        name: "[Actual payment: KRW 1.67 million / 30-day trial available] LG Gram Pro 16ZD90SP-GX56K Ultra5 16GB 256GB Windows not included",
        imgUrl: "/assets/lg_pc.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 2,
        name: "[Actual payment: KRW 1.67 million / 30-day trial available] LG Gram Pro 16ZD90SP-GX56K Ultra5 16GB 256GB Windows not included",
        imgUrl: "/assets/lg_pc.jpeg",
        price: "599.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 3,
        name: "[Actual payment: KRW 1.67 million / 30-day trial available] LG Gram Pro 16ZD90SP-GX56K Ultra5 16GB 256GB Windows not included",
        imgUrl: "/assets/lg_pc.jpeg",
        price: "99.99",
        discount: "",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 4,
        name: "[Actual payment: KRW 1.67 million / 30-day trial available] LG Gram Pro 16ZD90SP-GX56K Ultra5 16GB 256GB Windows not included",
        imgUrl: "/assets/lg_pc.jpeg",
        price: "299.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
    {
        id: 5,
        name: "[Actual payment: KRW 1.67 million / 30-day trial available] LG Gram Pro 16ZD90SP-GX56K Ultra5 16GB 256GB Windows not included",
        imgUrl: "/assets/lg_pc.jpeg",
        price: "49.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: false,
    },
];

export const section_macbook = [
    {
        id: 1,
        name: "MacBook Air M2 Midnight 2022 8-core CPU and 10-core GPU 512GB MLY43KH/A",
        imgUrl: "/assets/macbook_1.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: true,
    },
    {
        id: 2,
        name: "MacBook Air M2 Silver 2022 8-core CPU and 10-core GPU 512GB MLY03KH/A",
        imgUrl: "/assets/macbook_2.jpeg",
        price: "499.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: true,
    },
    {
        id: 3,
        name: "MacBook Air M2 Space Gray 2022 8-core CPU and 10-core GPU 512GB MLXX3KH/A",
        imgUrl: "/assets/macbook_3.jpeg",
        price: "1999.99",
        discount: "",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: true,
    },
    {
        id: 4,
        name: "MacBook Air M2 Space Gray 2022 8-core CPU and 10-core GPU 512GB MLXX3KH/A",
        imgUrl: "/assets/macbook_2.jpeg",
        price: "499.99",
        discount: "2% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: true,
    },
    {
        id: 5,
        name: "MacBook Air M2 Midnight 2022 8-core CPU and 10-core GPU 512GB MLY43KH/A",
        imgUrl: "/assets/macbook_1.jpeg",
        price: "499.99",
        discount: "21% ",
        like: 5,
        isDiscount: false,
        isSupprised: false,
        isReturned: true,
    },
];
